### ISSUE TITLE
DEP: q2-fragment-insertion can't be upgraded to Python 3.10, due to pinned SEPP dependency on Python <=3.9

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-fragment-insertion#88]
[Here's](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/sepp/meta.yaml#L24) the relevant pin. This will need to be addressed for q2-fragment-insertion to stay in the amplicon distribution when QIIME 2 transitions its Python version to 3.10 (planned for the 2024.10 release, which is currently scheduled for 2 October 2024).

**Comment by sjanssen2** [comment]
Hi @gregcaporaso. It is pinned to 3.9 because [SEPP](https://github.com/smirarab/sepp), not the q2 plugin was incompatible with py3.10 in its last release. 

It has meanwhile been fixed, but no new release was created. I asked for a new release some hours ago: https://github.com/smirarab/sepp/pull/136

For the meantime, I tried to simply source the bioconda recipe from HEAD instead of a release, however the bioconda CI service is "broken" at the moment: https://github.com/bioconda/bioconda-recipes/issues/41025

**Comment by gregcaporaso** [comment]
Thanks @sjanssen2. We have a little bit of time for a fix for this. We are going to start the transition to Python 3.10 this summer. If you hear of updates, it would be great if you could share here.

**Comment by sjanssen2** [comment]
This problem should be solved now: new bioconda packages for py3.10 are now available

**Comment by gregcaporaso** [comment]
Thanks @sjanssen2! We'll check it out and follow-up if needed. Really appreciate your efforts on this!

**Comment by lizgehret** [comment]
I'm going to close this as completed - per https://github.com/qiime2/distributions/pull/367 we have a working amplicon metapackage build for python 3.10!
